"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, ChevronRight, CircleHelp, Copy, Crown, Fuel, Heart, Package, Rocket, Shield, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import type { Crisis, Effect, ResourceKey } from "@/lib/game-data";

type Agenda = { Title: string; Brief: string; Rule: string };
type Player = { PlayerId: string; PlayerName: string; IsHost: boolean; HasVoted: boolean; Agenda?: Agenda | null; AgendaComplete?: boolean; Score?: number };
type GameState = {
  Room: { RoomCode: string; Phase: "Lobby" | "Voting" | "Result" | "GameOver"; RoundNumber: number; Fuel: number; Hull: number; Supplies: number; Morale: number; WinningOption: number | null; ResultText: string | null; Version: number };
  Me: { PlayerId: string; PlayerName: string; IsHost: boolean; HasVoted: boolean; Vote: number | null; Agenda: Agenda | null };
  Players: Player[]; Crisis: Crisis | null;
};

const resources: { key: ResourceKey; label: string; Icon: typeof Fuel; color: string }[] = [
  { key: "Fuel", label: "Fuel", Icon: Fuel, color: "#39d8ff" }, { key: "Hull", label: "Hull", Icon: Shield, color: "#76f4b2" },
  { key: "Supplies", label: "Supplies", Icon: Package, color: "#ffb84a" }, { key: "Morale", label: "Morale", Icon: Heart, color: "#ff6f91" },
];

function EffectList({ effect }: { effect: Effect }) { return <div className="effect-list">{Object.entries(effect).map(([key, value]) => <span className={Number(value) > 0 ? "positive" : "negative"} key={key}>{Number(value) > 0 ? "+" : ""}{value} {key}</span>)}</div>; }
function Brand() { return <div className="brand"><span className="brand-mark"><Rocket size={20} /></span><span><b>FINAL VOYAGE</b><small>COMMAND NETWORK</small></span></div>; }
function Rules() { return <Dialog><DialogTrigger asChild><Button variant="ghost" className="rules-button"><CircleHelp size={17} /> How to play</Button></DialogTrigger><DialogContent className="rules-dialog"><DialogHeader><DialogTitle>Mission protocol</DialogTitle><DialogDescription>Survive six crises without letting any ship resource reach zero.</DialogDescription></DialogHeader><div className="rules-warning"><AlertTriangle size={18} /><b>If Fuel, Hull, Supplies, or Morale reaches 0, the voyage ends immediately.</b></div><div className="rules-resources"><span><Fuel size={17} /><b>Fuel</b><small>Keeps the ship moving</small></span><span><Shield size={17} /><b>Hull</b><small>Protects the ship</small></span><span><Package size={17} /><b>Supplies</b><small>Feeds and equips the crew</small></span><span><Heart size={17} /><b>Morale</b><small>Keeps the crew united</small></span></div><ol className="rules-list"><li><span>1</span><p><b>Read the crisis.</b> Every round creates a new threat with three possible responses.</p></li><li><span>2</span><p><b>Discuss your options.</b> Your private agenda may give you a reason to protect one resource.</p></li><li><span>3</span><p><b>Vote privately.</b> The majority decision changes the ship. The captain breaks tied votes.</p></li><li><span>4</span><p><b>Survive six rounds.</b> Crew survival is worth more than any private objective.</p></li></ol><p className="rules-note">Private agendas award bonus points. They never require destroying the ship.</p></DialogContent></Dialog>; }

export default function Home() {
  const [name, setName] = useState(""); const [joinCode, setJoinCode] = useState("");
  const [identity, setIdentity] = useState<{ RoomCode: string; PlayerId: string } | null>(null);
  const [game, setGame] = useState<GameState | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [exitDialogOpen, setExitDialogOpen] = useState(false);
  useEffect(() => {
    const restoreIdentity = window.setTimeout(() => {
      try { const saved = localStorage.getItem("final-voyage-player"); if (saved) setIdentity(JSON.parse(saved)); } catch {}
    }, 0);
    return () => window.clearTimeout(restoreIdentity);
  }, []);
  const request = useCallback(async (payload: Record<string, unknown>) => { const response = await fetch("/api/game", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.Error ?? "Transmission failed."); return data; }, []);
  const refresh = useCallback(async () => { if (!identity) return; try { const response = await fetch(`/api/game?RoomCode=${identity.RoomCode}&PlayerId=${identity.PlayerId}`, { cache: "no-store" }); if (response.status === 404) { localStorage.removeItem("final-voyage-player"); setGame(null); setIdentity(null); setError("The captain closed the lobby."); return; } if (!response.ok) throw new Error(); setGame(await response.json()); setError(""); } catch { setError("Connection interrupted. Retrying…"); } }, [identity]);
  useEffect(() => {
    if (!identity) return;
    const initialRefresh = window.setTimeout(refresh, 0);
    const timer = window.setInterval(refresh, 1500);
    return () => { window.clearTimeout(initialRefresh); window.clearInterval(timer); };
  }, [identity, refresh]);
  async function enter(Action: "Create" | "Join") { setBusy(true); setError(""); try { const result = await request({ Action, PlayerName: name, RoomCode: joinCode }); const next = { RoomCode: result.RoomCode, PlayerId: result.PlayerId }; localStorage.setItem("final-voyage-player", JSON.stringify(next)); setIdentity(next); } catch (e) { setError(e instanceof Error ? e.message : "Unable to connect."); } finally { setBusy(false); } }
  async function act(Action: string, extra: Record<string, unknown> = {}) { if (!identity || busy) return; setBusy(true); setError(""); try { const next = await request({ Action, ...identity, ...extra }); if (next?.Room) setGame(next); } catch (e) { setError(e instanceof Error ? e.message : "Command failed."); } finally { setBusy(false); } }
  function clearLocalGame() { localStorage.removeItem("final-voyage-player"); setIdentity(null); setGame(null); setName(""); setExitDialogOpen(false); }
  async function confirmLeave() {
    if (!identity || busy) return;
    const ClosingLobby = game?.Room.Phase === "Lobby" && game.Me.IsHost;
    setBusy(true); setError("");
    try { await request({ Action: ClosingLobby ? "CloseLobby" : "LeaveGame", ...identity }); clearLocalGame(); }
    catch (e) { setError(e instanceof Error ? e.message : "Unable to leave the room."); }
    finally { setBusy(false); }
  }

  if (!identity) return <main className="home-shell"><div className="stars" /><header className="topbar"><Brand /><Rules /></header><section className="entry-grid"><div className="mission-copy"><p className="eyebrow">COOPERATIVE MULTIPLAYER STRATEGY</p><h1>Make it home.<br /><em>Keep your agenda.</em></h1><p>Your ship is failing. Vote through six crises while protecting Fuel, Hull, Supplies, and Morale. Every crew member also has a private resource objective.</p><div className="failure-rule"><AlertTriangle size={19} /><span><b>One resource reaches zero, the voyage is over.</b> Keep all four systems alive through the sixth crisis.</span></div><div className="mission-facts"><span><Users size={18} /> 3–5 players</span><span><Shield size={18} /> 6 crisis rounds</span><span><Rocket size={18} /> No accounts</span></div></div><div className="entry-panel"><div className="signal-line"><span /> SECURE CREW CHANNEL <span /></div><label>YOUR CALLSIGN</label><Input value={name} onChange={(e) => setName(e.target.value)} maxLength={20} placeholder="Enter your name" /><Button className="primary-action" disabled={busy} onClick={() => enter("Create")}><Rocket size={18} /> Create a voyage</Button><div className="or"><span />or join a crew<span /></div><label>ROOM CODE</label><div className="join-row"><Input value={joinCode} onChange={(e) => setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 5))} placeholder="ABCDE" className="code-input" /><Button disabled={busy || joinCode.length !== 5} onClick={() => enter("Join")}>Join</Button></div>{error && <p className="error"><AlertTriangle size={16} />{error}</p>}<p className="fine-print">Open this page on each player’s phone or laptop.</p></div></section></main>;
  if (!game) return <main className="loading-shell"><Brand /><div className="radar" /><p>Locating crew channel…</p>{error && <Button variant="outline" onClick={clearLocalGame}>Return home</Button>}</main>;

  const { Room, Me, Players, Crisis } = game; const shipAlive = resources.every((r) => Room[r.key] > 0); const winner = Room.WinningOption !== null && Crisis ? Crisis.Options[Room.WinningOption] : null;
  const closingLobby = Room.Phase === "Lobby" && Me.IsHost;
  const replacementCaptain = Players.find((player) => player.PlayerId !== Me.PlayerId)?.PlayerName;
  return <main className="game-shell"><div className="stars" /><header className="game-header"><Brand /><div className="room-pill"><span>ROOM</span><b>{Room.RoomCode}</b><button aria-label="Copy room code" onClick={() => { navigator.clipboard.writeText(Room.RoomCode); setCopied(true); setTimeout(() => setCopied(false), 1200); }}>{copied ? <Check size={16} /> : <Copy size={16} />}</button></div><div className="header-actions"><Rules />{Room.Phase !== "Lobby" && Room.Phase !== "GameOver" && <button className="leave-game" onClick={() => setExitDialogOpen(true)}>Leave game</button>}</div></header>
    {Room.Phase !== "Lobby" && <section className="status-deck"><div className="round-indicator"><span>VOYAGE PROGRESS</span><b>{Room.Phase === "GameOver" ? "MISSION COMPLETE" : `CRISIS ${Room.RoundNumber} OF 6`}</b><div>{Array.from({ length: 6 }, (_, i) => <i className={i < Room.RoundNumber ? "active" : ""} key={i} />)}</div></div><div className="resource-grid">{resources.map(({ key, label, Icon, color }) => <div className={`resource ${Room[key] <= 2 ? "critical" : ""}`} key={key}><div><Icon size={17} style={{ color }} /><span>{label}</span><b>{Room[key]}<small>/10</small></b></div><div className="meter"><i style={{ width: `${Room[key] * 10}%`, background: color }} /></div></div>)}</div></section>}
    {Room.Phase === "Lobby" && <section className="lobby-layout"><div className="lobby-main panel"><p className="eyebrow">CREW ASSEMBLY</p><h1>Awaiting launch clearance</h1><p>Share the room code with up to four other players. The captain can launch once at least three crew members are connected.</p><div className="large-code"><span>{Room.RoomCode}</span><Button variant="outline" onClick={() => navigator.clipboard.writeText(Room.RoomCode)}><Copy size={17} /> Copy</Button></div><div className="crew-grid">{Players.map((p) => <div className="crew-card" key={p.PlayerId}><span>{p.PlayerName.slice(0, 1).toUpperCase()}</span><div><b>{p.PlayerName}</b><small>{p.IsHost ? "Captain" : "Crew member"}</small></div>{p.IsHost && <Crown size={17} />}</div>)}{Players.length < 5 && <div className="crew-card empty"><span>+</span><div><b>Open station</b><small>{5 - Players.length} {5 - Players.length === 1 ? "seat" : "seats"} remaining</small></div></div>}</div>{Me.IsHost ? <Button className="primary-action launch" disabled={busy || Players.length < 3} onClick={() => act("Start")}><Rocket size={18} /> Launch voyage</Button> : <div className="waiting"><i /> Waiting for the captain to launch…</div>}<button className="leave" onClick={() => setExitDialogOpen(true)}>{Me.IsHost ? "Close lobby" : "Leave room"}</button></div><aside className="agenda-preview panel"><Shield size={28} /><h2>One crew. Private priorities.</h2><p>At launch, each player receives a secret agenda. Keep the ship alive while steering decisions toward your objective.</p><ul><li>Discuss every crisis</li><li>Vote from your own device</li><li>Keep every resource above zero</li><li>Survive all six rounds</li></ul></aside></section>}
    {(Room.Phase === "Voting" || Room.Phase === "Result") && Crisis && <section className="play-layout"><aside className="secret-panel panel"><p className="eyebrow">CLASSIFIED AGENDA</p><Shield size={31} /><h2>{Me.Agenda?.Title}</h2><p>{Me.Agenda?.Brief}</p><div>{Me.Agenda?.Rule}</div><small>Only you can see this objective.</small><hr /><h3>CREW STATUS</h3>{Players.map((p) => <div className="crew-status" key={p.PlayerId}><span>{p.PlayerName.slice(0, 1).toUpperCase()}</span><b>{p.PlayerName}</b>{p.HasVoted ? <Check size={16} /> : <i />}</div>)}</aside><article className="crisis-panel"><div className="crisis-heading"><div><p className="eyebrow">INCOMING TRANSMISSION · {Crisis.Category.toUpperCase()}</p><h1>{Crisis.Title}</h1></div><span>0{Room.RoundNumber}</span></div><blockquote>{Crisis.Transmission}</blockquote>{Room.Phase === "Voting" ? <><p className="instruction">Discuss the consequences, then cast your private vote.</p><div className="option-grid">{Crisis.Options.map((choice, index) => <button className={`option-card ${Me.Vote === index ? "selected" : ""}`} disabled={busy || Me.HasVoted} onClick={() => act("Vote", { Option: index })} key={choice.Title}><span className="option-letter">{String.fromCharCode(65 + index)}</span><div><h3>{choice.Title}</h3><p>{choice.Detail}</p><EffectList effect={choice.Effect} /></div>{Me.Vote === index && <Check className="selection-check" size={18} />}</button>)}</div>{Me.HasVoted && <div className="vote-locked"><Check size={18} /><span><b>Vote locked</b> Waiting for {Players.filter((p) => !p.HasVoted).length || "the ship"} {Players.filter((p) => !p.HasVoted).length === 1 ? "crew member" : "crew members"}…</span></div>}</> : <div className="resolution"><p className="eyebrow">CREW DECISION</p><div className="resolution-icon"><Check size={27} /></div><h2>{winner?.Title}</h2><p>{Room.ResultText}</p>{winner && <EffectList effect={winner.Effect} />}{Me.IsHost ? <Button className="primary-action" disabled={busy} onClick={() => act("Advance")}>{Room.RoundNumber >= 6 || !shipAlive ? "View mission report" : "Continue voyage"}<ChevronRight size={18} /></Button> : <div className="waiting"><i /> Waiting for the captain…</div>}</div>}</article></section>}
    {Room.Phase === "GameOver" && <section className="endgame"><div className={`outcome-emblem ${shipAlive ? "success" : "failure"}`}>{shipAlive ? <Rocket size={42} /> : <AlertTriangle size={42} />}</div><p className="eyebrow">FINAL MISSION REPORT</p><h1>{shipAlive ? "Earth is in sight." : "The voyage has ended."}</h1><p>{shipAlive ? "Against every crisis, the crew brought the ship home." : "A critical ship system reached zero before the crew could reach Earth."}</p><div className="scoreboard panel">{[...Players].sort((a, b) => (b.Score ?? 0) - (a.Score ?? 0)).map((p, index) => <div className="score-row" key={p.PlayerId}><b className="rank">{index + 1}</b><span className="avatar">{p.PlayerName.slice(0, 1).toUpperCase()}</span><div className="score-details"><div className="score-name"><h3>{p.PlayerName}{p.PlayerId === Me.PlayerId && <small> YOU</small>}</h3><span className={p.AgendaComplete ? "agenda-complete" : "agenda-incomplete"}>{p.AgendaComplete ? "Complete" : "Incomplete"}</span></div><div className="agenda-reveal"><b>{p.Agenda?.Title ?? "Unknown agenda"}</b>{p.Agenda?.Brief && <p>{p.Agenda.Brief}</p>}{p.Agenda?.Rule && <small>{p.Agenda.Rule}</small>}</div></div><strong>{p.Score}<small> PTS</small></strong></div>)}</div>{Me.IsHost ? <Button className="primary-action replay" disabled={busy} onClick={() => act("Rematch")}><Rocket size={18} /> Return to lobby</Button> : <div className="waiting centered"><i /> Waiting for the captain to rematch…</div>}</section>}
    <AlertDialog open={exitDialogOpen} onOpenChange={setExitDialogOpen}><AlertDialogContent className="exit-dialog"><AlertDialogHeader><AlertDialogTitle>{closingLobby ? "Close this lobby?" : Me.IsHost ? "Leave and transfer captain?" : "Leave the game?"}</AlertDialogTitle><AlertDialogDescription>{closingLobby ? "Every crew member will be returned to the home screen. This cannot be undone." : Me.IsHost ? `You will leave the voyage. Captain controls will pass to ${replacementCaptain ?? "another crew member"}.` : "You will be removed from the crew and returned home."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={(event) => { event.preventDefault(); void confirmLeave(); }}>{busy ? "Leaving…" : closingLobby ? "Close lobby" : Me.IsHost ? "Leave and transfer captain" : "Leave game"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {error && <div className="toast-error"><AlertTriangle size={16} />{error}</div>}
  </main>;
}
