export type ResourceKey = "Fuel" | "Hull" | "Supplies" | "Morale";
export type Effect = Partial<Record<ResourceKey, number>>;
export type CrisisOption = { Title: string; Detail: string; Effect: Effect };
export type Crisis = { Id: number; Category: string; Title: string; Transmission: string; Options: [CrisisOption, CrisisOption, CrisisOption] };

const option = (Title: string, Detail: string, Effect: Effect): CrisisOption => ({ Title, Detail, Effect });

export const Crises: Crisis[] = [
  { Id: 1, Category: "External", Title: "Distress Signal", Transmission: "A damaged civilian vessel is broadcasting for immediate assistance.", Options: [option("Attempt a rescue", "Dock and bring the survivors aboard.", { Fuel: -2, Morale: 2 }), option("Send remote supplies", "Transfer what they need and keep moving.", { Supplies: -2, Morale: 1 }), option("Maintain course", "Earth is still a long way away.", { Morale: -2 })] },
  { Id: 2, Category: "Engineering", Title: "Reactor Coolant Leak", Transmission: "Coolant pressure is dropping. The engine can hold, but not without a sacrifice.", Options: [option("Emergency shutdown", "Protect the reactor and drift off course.", { Fuel: -2, Hull: 1 }), option("Patch it manually", "Use scarce repair materials.", { Supplies: -2, Hull: 2 }), option("Run it hot", "Keep speed and accept the damage.", { Hull: -2, Morale: -1 })] },
  { Id: 3, Category: "Navigation", Title: "The Kestrel Field", Transmission: "A dense asteroid belt blocks the shortest route home.", Options: [option("Thread the field", "Save fuel, risk the hull.", { Hull: -2, Fuel: 1 }), option("Take the long route", "A safer path with a heavy fuel cost.", { Fuel: -2 }), option("Burn through", "Maximum thrust may protect confidence.", { Fuel: -1, Hull: -1, Morale: 1 })] },
  { Id: 4, Category: "Crew", Title: "Galley Contamination", Transmission: "A storage seal failed and part of the food supply may be unsafe.", Options: [option("Discard everything", "No one gets sick, but stores run low.", { Supplies: -2, Morale: 1 }), option("Test and ration", "Stretch what remains under strict controls.", { Supplies: -1, Morale: -1 }), option("Trust the scanners", "Keep the food and accept uncertainty.", { Morale: -2 })] },
  { Id: 5, Category: "External", Title: "Silent Research Station", Transmission: "An abandoned station appears intact. Its docking lights still pulse.", Options: [option("Search the station", "Useful stores may still be aboard.", { Supplies: 2, Fuel: -1, Morale: -1 }), option("Salvage the exterior", "Take hull plating without entering.", { Hull: 1, Fuel: -1 }), option("Leave it behind", "Unknown stations create unknown risks.", { Morale: -1 })] },
  { Id: 6, Category: "Crew", Title: "Sleepless Watch", Transmission: "The crew is exhausted, and navigation errors are increasing.", Options: [option("Mandatory rest", "Slow the ship while everyone recovers.", { Fuel: -1, Morale: 2 }), option("Issue stimulants", "Spend medical stores to stay alert.", { Supplies: -2, Morale: 1 }), option("Push onward", "The schedule matters more than comfort.", { Morale: -2, Hull: -1 })] },
  { Id: 7, Category: "Engineering", Title: "Fractured Solar Array", Transmission: "One array is tearing free and striking the outer hull.", Options: [option("Spacewalk repair", "Consume equipment and restore it.", { Supplies: -2, Hull: 2 }), option("Jettison the array", "Stop the damage and lose efficiency.", { Fuel: -2, Hull: 1 }), option("Secure it remotely", "Fast, but imperfect.", { Hull: -1, Morale: -1 })] },
  { Id: 8, Category: "Navigation", Title: "Gravity Well", Transmission: "An uncharted moon is pulling the ship away from its plotted course.", Options: [option("Full counter-burn", "Escape quickly at high fuel cost.", { Fuel: -2, Morale: 1 }), option("Slingshot around it", "Risk the hull to conserve fuel.", { Hull: -2, Fuel: 1 }), option("Correct gradually", "A measured response strains everyone.", { Fuel: -1, Morale: -1 })] },
  { Id: 9, Category: "Resource", Title: "Frozen Water Reserve", Transmission: "The primary water tank has frozen solid after a thermal failure.", Options: [option("Divert engine heat", "Restore water while reducing efficiency.", { Fuel: -2, Supplies: 2 }), option("Break into reserves", "Use emergency packs.", { Supplies: -2, Morale: 1 }), option("Strict rationing", "Conserve what is accessible.", { Morale: -2 })] },
  { Id: 10, Category: "External", Title: "Automated Toll Beacon", Transmission: "An old defense network demands payment before allowing passage.", Options: [option("Pay in supplies", "Comply and move safely through.", { Supplies: -2 }), option("Detour around it", "Avoid conflict at a fuel cost.", { Fuel: -2 }), option("Run the blockade", "Keep resources and take fire.", { Hull: -2, Morale: 1 })] },
  { Id: 11, Category: "Crew", Title: "A Voice from Home", Transmission: "A weak transmission from Earth reaches the crew, but receiving it drains reserve power.", Options: [option("Play it for everyone", "The crew needs hope.", { Fuel: -1, Morale: 2 }), option("Archive the message", "Save it for the final approach.", { Morale: -1 }), option("Reply immediately", "Send proof that the crew is alive.", { Fuel: -2, Morale: 2 })] },
  { Id: 12, Category: "Engineering", Title: "Cargo Bay Breach", Transmission: "A micrometeor tears through the cargo deck and atmosphere is escaping.", Options: [option("Seal the entire bay", "Lose stored materials but save the hull.", { Supplies: -2, Hull: 1 }), option("Deploy repair foam", "Spend materials on a permanent patch.", { Supplies: -1, Hull: 2 }), option("Vent and isolate", "Accept damage to preserve cargo.", { Hull: -2 })] },
  { Id: 13, Category: "Navigation", Title: "False Star Map", Transmission: "The navigation archive contains two incompatible routes to Earth.", Options: [option("Trust the old charts", "Proven, but longer.", { Fuel: -2 }), option("Trust the new charts", "Shorter, through unstable space.", { Hull: -1, Fuel: 1 }), option("Recalculate manually", "Spend time and exhaust the crew.", { Morale: -2, Fuel: 1 })] },
  { Id: 14, Category: "Resource", Title: "Medical Shortage", Transmission: "Several crew members need the last advanced treatment kits.", Options: [option("Treat everyone now", "Use the remaining medical stock.", { Supplies: -2, Morale: 2 }), option("Treat critical cases", "Preserve some stock for later.", { Supplies: -1 }), option("Save the kits", "The final approach may be worse.", { Morale: -2 })] },
  { Id: 15, Category: "External", Title: "Unknown Escort", Transmission: "An unidentified vessel offers to guide the ship through a storm.", Options: [option("Accept the escort", "Follow their route and share supplies.", { Supplies: -1, Hull: 2 }), option("Decline politely", "Navigate independently.", { Fuel: -1, Hull: -1 }), option("Flee at full speed", "Lose them and burn reserves.", { Fuel: -2, Morale: 1 })] },
  { Id: 16, Category: "Crew", Title: "Command Dispute", Transmission: "Two officers openly disagree about the mission's priorities.", Options: [option("Hold a crew vote", "Give everyone a voice despite the delay.", { Fuel: -1, Morale: 2 }), option("Back the captain", "Restore order quickly.", { Morale: -1 }), option("Split responsibilities", "Compromise at the cost of supplies.", { Supplies: -1, Morale: 1 })] },
  { Id: 17, Category: "Engineering", Title: "Life Support Overload", Transmission: "The scrubbers cannot support every occupied deck at full capacity.", Options: [option("Close recreation", "Protect essentials and hurt morale.", { Morale: -2, Supplies: 1 }), option("Install spare filters", "Use critical repair stock.", { Supplies: -2, Hull: 1 }), option("Reduce engine output", "Save the scrubbers and lose progress.", { Fuel: -2, Morale: 1 })] },
  { Id: 18, Category: "Navigation", Title: "Ion Storm", Transmission: "A violent storm will overtake the ship before the next jump point.", Options: [option("Outrun the storm", "Burn fuel to reach clear space.", { Fuel: -2, Morale: 1 }), option("Reinforce the hull", "Use stores and ride it out.", { Supplies: -2, Hull: 1 }), option("Shelter in place", "Save resources and absorb damage.", { Hull: -2, Morale: -1 })] },
  { Id: 19, Category: "Resource", Title: "Fuel Cell Fire", Transmission: "A reserve fuel cell ignites beside the emergency supply lockers.", Options: [option("Flood the compartment", "Save fuel and ruin nearby supplies.", { Supplies: -2, Fuel: 1 }), option("Eject the fuel cell", "Protect the ship but lose fuel.", { Fuel: -2, Hull: 1 }), option("Fight it manually", "Risk damage to preserve resources.", { Hull: -2, Morale: 1 })] },
  { Id: 20, Category: "External", Title: "The Last Jump Gate", Transmission: "A failing gate could shorten the final leg, but it may collapse during transit.", Options: [option("Take the gate", "Risk the hull for a fuel gain.", { Hull: -2, Fuel: 2 }), option("Go around", "Choose certainty at a fuel cost.", { Fuel: -2 }), option("Stabilize then jump", "Spend supplies to reduce the risk.", { Supplies: -2, Fuel: 1 })] },
];

export const Agendas = [
  { Title: "The Navigator", Brief: "Bring them home with fuel to spare.", Rule: "Finish with at least 5 Fuel." },
  { Title: "The Engineer", Brief: "The ship itself is your responsibility.", Rule: "Finish with at least 6 Hull." },
  { Title: "The Quartermaster", Brief: "A living crew needs full lockers.", Rule: "Finish with at least 5 Supplies." },
  { Title: "The Idealist", Brief: "Survival means little without hope.", Rule: "Finish with at least 7 Morale." },
  { Title: "The Survivor", Brief: "You refuse to gamble with extinction.", Rule: "Keep every resource at 3 or higher." },
  { Title: "The Opportunist", Brief: "A close call makes a better story.", Rule: "Finish with exactly one resource at 2 or lower." },
  { Title: "The Reserve Officer", Brief: "The final approach cannot begin on empty tanks.", Rule: "Finish with Fuel as the highest or tied-highest resource." },
  { Title: "The Guardian", Brief: "A strong ship needs both steel and spirit.", Rule: "Finish with Hull and Morale totaling at least 11." },
  { Title: "The Conservationist", Brief: "Waste will doom this voyage.", Rule: "Finish with Fuel and Supplies totaling at least 10." },
  { Title: "The Shipwright", Brief: "Metal can be repaired. Lives cannot.", Rule: "Finish with Hull higher than Fuel." },
  { Title: "The Steward", Brief: "The crew must arrive ready to rebuild.", Rule: "Finish with Morale and Supplies both at 5 or higher." },
  { Title: "The Balancer", Brief: "No single system should carry the ship.", Rule: "Finish with all resources within 3 points of one another." },
] as const;

export function agendaComplete(AgendaId: number | null, room: Record<ResourceKey, number>) {
  const values = [room.Fuel, room.Hull, room.Supplies, room.Morale];
  switch (AgendaId) {
    case 0: return room.Fuel >= 5; case 1: return room.Hull >= 6; case 2: return room.Supplies >= 5; case 3: return room.Morale >= 7;
    case 4: return values.every((v) => v >= 3); case 5: return values.filter((v) => v <= 2).length === 1;
    case 6: return room.Fuel === Math.max(...values); case 7: return room.Hull + room.Morale >= 11; case 8: return room.Fuel + room.Supplies >= 10;
    case 9: return room.Hull > room.Fuel; case 10: return room.Morale >= 5 && room.Supplies >= 5; case 11: return Math.max(...values) - Math.min(...values) <= 3;
    default: return false;
  }
}
